### ISSUE TITLE
[BUG] MessageServer not handling unexpected client disconnects correctly

### ISSUE THREAD

**Issue by threeeye** [Johno-ACSLive/ACS-Messaging#1]
**Describe the bug**
When a client unexpectedly disconnects from the server (client crashes), the sever doesn't know how to handle it.
Error message: "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."
on line: byteCount = await stream.ReadAsync(buffer, 0, buffer.Count()).ConfigureAwait(false);
This is also true if the server crashes.

**To Reproduce**
Just kill the client or server

**Expected behavior**
If the client crashes, the server should remove that client.
If the server crashes, all clients should wait for the server to come back, and reconnect to it.

**Environment (please complete the following information):**
Windows 10 LTSC 2021
.NET Framework 4.7.2

**Comment by Johno-ACSLive** [comment]
Server has been fixed, the correction was already implemented for the client. Looks like I originally missed refactoring the server side. Commit b14982a7bc94df5dadce830947fff79ea94d011c should resolve the issue.

I've also added a sample project for client and server. The sample is using .NET 6 so hopefully the library fix will work with .NET 4.7.2 as well.

Please confirm if the fix is working on your end.

**Comment by threeeye** [comment]
Sorry for the late reply.
I just tested it, and it works grate!
Thanks
