### ISSUE TITLE
[BUG] Server doesn't remove the Client on ConnectionClosed

### ISSUE THREAD

**Issue by threeeye** [Johno-ACSLive/ACS-Messaging#3]
**Describe the bug**
I noticed that when a Client disconnects from the Server, most of the time the Server doesn't remove the Client on ConnectionClosed.
Background: I have a Service app that acts as a Client and a Server (Client to the main Server app, and Server for the Tray Icon app - because a service can't have a GUI).
The Tray app closes the connection on user lock (SystemEvents_SessionSwitch), and reconnects on user unlock.
When I request data from the Server, I get it as much times that I locked and unlocked the user (once at the begging, 2 times after 1st unlock, 3 times after 2nd unlock...)

P.S.
I may be doing something wrong...

**Expected behavior**
Every time the Client disconnects, the Server should remove that Client

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC 2021
 - Framework Type: .NET Framework
 - Framework Version: 4.8

**Comment by Johno-ACSLive** [comment]
Not a problem, let me investigate.

**Comment by Johno-ACSLive** [comment]
I can't see a reason for that to occur, the server will always remove a client.

When a client cleanly (or uncleanly) disconnects there will be a 0 byte count. At that point the client is removed and the connection closed event occurs.

Without seeing a mock-up of your code it's hard to say where the problem is. Does the server see a connection closed event when you lock?

If so, can you print the number of clients and confirm it's 0?

If not, how are you disconnecting? You need to call the Dispose method for client to actually be disconnected.

**Comment by threeeye** [comment]
Thanks for looking into it.
The Client is the one that sees the Lock event (the Server is a Service app).
On the Client:
```
Private Sub SystemEvents_SessionSwitch(sender As Object, e As SessionSwitchEventArgs)
        Select Case e.Reason
            Case SessionSwitchReason.SessionLock
                StartThread.Abort()
                MsgBox(StartThread.ThreadState)
            Case SessionSwitchReason.SessionUnlock
                Thread.Sleep(1000)

                StartThread = New Thread(AddressOf Connect)
                StartThread.Start()
        End Select
End Sub
```

The message box is there just to get the state of the thread, I get 256 (The thread state includes AbortRequested and the thread is now dead, but its state has not yet changed to Stopped.)
I also tried to put "Client.Dispose()" before the "StartThread.Abort()"
But the Server still has the old Clients ( I have the server sending the client a "TrayServer.Hosts.Count"), and each time I lock and unlock the computer, I have another client in the count...

P.S.
Closing the Client app does remove the Client from the server, I'm starting to think that the thread is not stopping...

**Comment by Johno-ACSLive** [comment]
Yeah this is looking like a threading issue (depending on how the rest of your code is written you may not be able to access the Client instance from the thread you are on and you wouldn't necessarily be able to call Dispose in the thread since it's being aborted). I'd recommend switching to using Tasks and await/async as they can provide more flexibility and the option of passing a cancellation token. In that case you may receive an exception (depending on how the task is written) and use it to Dispose the Client before the Task exits.

Having said that, not sure I see a reason to use threads/tasks here or connect/disconnect but it depends on what your Connect function actually does. You could just connect on start-up and send a message to the backend on the state (locked or unlocked). Alternatively if you want to keep your current flow then you could just call a function which sets up a new client, another to cancel the client and use a task to perform some work and use the client.

**Comment by threeeye** [comment]
Yup, it's a threading issue.
When I remove the thread and run it outside of threading (Client.Connect() and Client.Dispose()) I don't have that issue.

Sorry for the bother

**Comment by Johno-ACSLive** [comment]
Not a problem.
